# Site settings
title: Computer Works of Ukiah
slogan: Maintaining Many Satisfied Customers!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.computerworksofukiah.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
